ExamNP/WebAPITask2/WebAPITask2/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using WebAPITask2.Areas.HelpPage.ModelDescriptions;

namespace WebAPITask2.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

ExamNP/WebAPITask2/WebAPITask2/Models/Letter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAPITask2.Models
{
    public class Letter
    {
        public string To { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }

    }
}

ExamNP/WebAPITask2/WebAPITask2/Models/SMSmodel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAPITask2.Models
{
    public class SMSmodel
    {
        public string PhoneNumber { get; set; }
        public string Body { get; set; }
        public string From { get; set; }
        public string Password { get; set; }

    }
}

ExamNP/WebAPITask2/WebAPITask2/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using WebAPITask2.Areas.HelpPage.ModelDescriptions;
using WebAPITask2.Areas.HelpPage.Models;

namespace WebAPITask2.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

ExamNP/WebAPITask2/WebAPITask2/Controllers/FileLoadController.cs
using System.Web.Http;

namespace WebAPITask2.Controllers
{
    public class FileLoadController : ApiController
    {
        public void Get(string path)
        {
           
        }
    }
}

ExamNP/WebAPITask2/WebAPITask2/Controllers/HomeController.cs
using System.Web.Mvc;

namespace WebAPITask2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

ExamNP/WebAPITask2/WebAPITask2/Controllers/MailController.cs
using System.Collections.Generic;
using System.Net.Mail;
using System.Web.Http;
using WebAPITask2.Models;
using WebAPITask2.SendHelper;

namespace WebAPITask2.Controllers
{
    public class MailController : ApiController
    {
        [HttpPost]
        public void SendMail([FromBody]Letter letter)
        {
            SendHelper.SendHelper.SendEmail(letter.To, letter.Subject, letter.Body);
        }
    }
}

ExamNP/WebAPITask2/WebAPITask2/Controllers/SMSController.cs
using System.Web.Http;
using WebAPITask2.Models;

namespace WebAPITask2.Controllers
{
    public class SMSController : ApiController
    {
        [HttpPost]
        public void SendSMS([FromBody]SMSmodel forSms)
        {
            SendHelper.SendHelper.SendSMS(forSms);
        }
    }
}

ExamNP/WebAPITask2/WebAPITask2/Views/Home/Index.cshtml
@model WebAPITask2.Models.Letter

@{
    ViewBag.Title = "Index";
}

<h2>Send emai:</h2>

   @using (Html.BeginForm("","api/mail"))
   {
        <table id="fff">
            <tr>
                <td><p>Please enter the email address: </p></td>
                <td><input type="email" name="To" /> </td>
            </tr>
            <tr>
                <td><p>Subject :</p></td>
                <td><input type="text" name="Subject" /> </td>
            </tr>
            <tr>
                <td><p>Body :</p></td>
                <td><input type="text" name="Body" /> </td>
            </tr>
            <tr>
                <td><input type="submit" value="Send" /> </td>
                <td></td>
            </tr>
        </table>
    }

<h2>Send SMS:</h2>

@using (Html.BeginForm("", "api/SMS"))
{
    <table id="fff">
        <tr>
            <td><p>Please enter the email address: </p></td>
            <td><input type="email" name="From" /> </td>
        </tr>
        <tr>
            <td><p>Phone :</p></td>
            <td><input type="text" name="PhoneNumber" /> </td>
        </tr>
        <tr>
            <td><p>Body :</p></td>
            <td><input type="text" name="Body" /> </td>
        </tr>
        <tr>
            <td>Password :</td>
            <td><input type="password" value="Password" /> </td>
        </tr>
        <tr>
            <td><input type="submit" value="Send" /> </td>
            <td></td>
        </tr>
    </table>
}

ExamNP/WebAPITask2/WebAPITask2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>